export type PropsActionType = {
    CLOSE_EDIT_TASK: "CLOSE_EDIT_TASK";
    CLOSE_DELETE_TASK: "CLOSE_DELETE_TASK";
    CLOSE_CREATE_TASK: "CLOSE_CREATE_TASK";
    CLOSE_CREATE_USER: "CLOSE_CREATE_USER";
    CLOSE_DELETE_USER: "CLOSE_DELETE_USER";
    CHECK_TASK: "CHECK_TASK";
};

export const actionsType: PropsActionType = {
    CLOSE_EDIT_TASK: "CLOSE_EDIT_TASK",
    CLOSE_DELETE_TASK: "CLOSE_DELETE_TASK",
    CLOSE_CREATE_TASK: "CLOSE_CREATE_TASK",
    CLOSE_CREATE_USER: "CLOSE_CREATE_USER",
    CLOSE_DELETE_USER: "CLOSE_DELETE_USER",
    CHECK_TASK: "CHECK_TASK",
};
